name : Python Selenium Tests

# 언제 실행할지 설정하는 것
on : 
   push :
     branches : ["master", "main"]
   pull_request:
     branches : ["master", "main"]  

jobs:
  test:
    runs-on : ubuntu-latest # GitHub Actions 실행 환경(Linux)
    timeout-minutes: 10 # 최대 10분까지만 실행

    # MySQL 서버를 임시로 띄우기 위해
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: '1111'
          MYSQL_DATABASE: 'qa_test'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 

    steps:
    - name : Checkout code
      uses : actions/checkout@v3

    - name : Set up Python
      uses : actions/setup-python@v4
      with : 
        python-version : '3.10'

    - name : Install dependencies
      run : |
        python -m pip install --upgrade pip
        pip install pytest allure-pytest selenium webdriver_manager pymysql

    - name : Run Tests and Collect Allure Data
      run : pytest --maxfail=1 --disable-warnings --alluredir=allure-results     

    - name : Upload Allure Results (Artifact)
      uses : actions/upload-artifact@v4
      with:
        name : allure-results
        path : allure-results