name : Python Selenium Tests

# 언제 실행할지 설정하는 것
on : 
   push :
     branches : [master]
   pull_request:
     branches : [master]  

jobs:
  test:
    runs-on : ubuntu-latest # GitHub Actions 실행 환경(Linux)
    timeout-minutes: 10 # 최대 10분까지만 실행

    steps:
    - name : Checkout code
      uses : actions/checkout@v3

    - name : Set up Python
      uses : actions/setup-python@v4
      with : 
        python-version : '3.10'

    - name : Install dependencies
      run : |
        pip install -r requirements.txt

    - name : Run Tests
      run : pytest -v --timeout=60 --maxfail=1 --disable-warnings -q     

    - name : Run Tests and Generate Report
      run : pytest --html=report.html --self-contained-html

    - name : Upload Test Report
      uses : actions/upload-artifact@v3.1.2
      with:
        name : pytest-report
        path : report.html