name : Python Selenium Tests

# 언제 실행할지 설정하는 것
on : 
   push :
     branches : ["master", "main"]
   pull_request:
     branches : ["master", "main"]  

jobs:
  test:
    runs-on : ubuntu-latest # GitHub Actions 실행 환경(Linux)
    timeout-minutes: 10 # 최대 10분까지만 실행

    # MySQL 서버를 임시로 띄우기 위해
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: '1111'
          MYSQL_DATABASE: 'qa_test'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 

    steps:
    - name : Checkout code
      uses : actions/checkout@v3

    - name : Set up Python
      uses : actions/setup-python@v4
      with : 
        python-version : '3.10'

    - name : Install dependencies
      run : |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name : Run Tests and Collect Allure Data
      run : pytest --maxfail=1 --disable-warnings --alluredir=allure-results   
    
    # 테스트 실행
    - name : Run E2E Tests with Allure
      # if : always()를 넣으면 앞의 테스트가 실패해도 리포트는 무조건 뽑힌다. 
      run : pytest api/ -s --alluredir=allure-results
      continue-on-error : true

    # Allure 결과물을 HTML 웹페이지 형태로 만들기
    - name : Generate Allure Report
      uses : simple-elf/allure-report-action@master
      if : always()
      with :
        allure_results : allure-results
        allure_history : allure-history
        keep_reports : 20

    # 만든 웹페이지를 GItHub Pages 브랜치(gh-pages)로 올리기
    - name : Deploy Allure Report to GitHub Pages
      uses : peaceiris/actions-gh-pages@v3
      if : always()
      with:
        github_token : ${{ secrets.GITHUB_TOKEN }}
        publish_branch : gh-pages
        publish_dir : allure-history

    - name : Upload Allure Results (Artifact)
      uses : actions/upload-artifact@v4
      with:
        name : allure-results
        path : allure-results