name : Python Selenium Tests

# 언제 실행할지 설정하는 것
on : 
   push :
     branches : [master]
   pull_request:
     branches : [master]  

jobs:
  test:
    runs-on : ubuntu-latest # GitHub Actions 실행 환경(Linux)

    steps:
    - name : Checkout code
      uses : actions/checkout@v3

    - name : Set up Python
      uses : actions/setup-python@v4
      with : 
        python-version : '3.10'

    - name : Install dependencies
      run : |
        pip install pytest selenium webdriver-manager

    - name : Run Tests
      run : pytest -v        